services:
  netalertx:
    image: ghcr.io/netalertx/netalertx:latest
    container_name: netalertx
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1026
      - PGID=100
      - PORT=20211
      - GRAPHQL_PORT=20212
      - LISTEN_ADDR=0.0.0.0
      - ALWAYS_FRESH_INSTALL=false
      - NETALERTX_DEBUG=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/netalertx:/data
