services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - /:/srv/root:rw
      - filebrowser_data:/database
    environment:
      - PUID=1000
      - PGID=1000
    user: "1000:1000"

volumes:
  filebrowser_data:
