services:
  netalertx:
    image: jokobsk/netalertx:latest
    container_name: netalertx
    restart: unless-stopped
    network_mode: host
    volumes:
      - netalertx_config:/app/config
      - netalertx_db:/app/db
    environment:
      - TZ=Europe/Amsterdam
      - PORT=20211

volumes:
  netalertx_config:
  netalertx_db:
