services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_RUN_ONCE=true
      - WATCHTOWER_CLEANUP=true
      - TZ=Europe/Amsterdam
      - DOCKER_API_VERSION=1.43
